version: '2.1'

volumes:
  mysql_data:
    external:
      name: "am-mysql-data"

services:

  elasticsearch:
    volumes:
      - "${ELASTIC_DAT_DIR}:/usr/share/elasticsearch/data"

  archivematica-storage-service:
    volumes:
      - "./archivematica_storage_service_staging_data:/var/archivematica/storage_service:rw"

