version: '2.1'

services:
  web:
    build: ./web
    restart: always
    tty: true
    links:
      - fpm
      - nginx
      - shib
    ports:
      - 80:80
      - 443:443
      - 8089:8089
    volumes:
      - run.php:/run/php
      - run.shibboleth:/run/shibboleth
      - filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp
      - ${NGINX_ICON_DIR:-./web/icon}:/opt/brand
      - ${NGINX_ETC_DIR:-./web/nginx/conf.d}:/etc/nginx/conf.d
      - ${SHIBBOLETH_ETC_DIR:-./shib/shibboleth}:/etc/shibboleth
      - ${NGINX_LOG_DIR:-./log/nginx}:/var/log/nginx

  fpm:
    image: 'uazlibraries/filesender-phpfpm:2.0-rc1'
    restart: always
    links:
      - mysql
    environment:
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com:587}
      - SMTP_TLS=${SMTP_TLS:-true}
      - SMTP_USER=${SMTP_USER:-dockertestfilesender}
      - SMTP_PSWD=${SMTP_PSWD:-thisisalongpassword}
      - ADMIN_EMAIL=${FILESENDER_ADMIN_EMAIL:-dockertestfilesender@gmail.com}
      - ADMIN_PSWD=${FILESENDER_ADMIN_PSWD:-password}
      - FILESENDER_URL=${FILESENDER_URL:-https://{PUBLICIP}/upload}
      - FILESENDER_LOGOUT_URL=${FILESENDER_LOGOUT_URL:-https://{PUBLICIP}}
      - FILESENDER_STORAGE=${FILESENDER_STORAGE:-FilesystemPreserveName}
      - FILESENDER_AUTHTYPE=${FILESENDER_AUTHTYPE:-shibboleth}
      - MAIL_ATTR=${FILESENDER_MAIL_ATTR:-EPPN}
      - NAME_ATTR=${FILESENDER_NAME_ATTR:-EPPN}
      - UID_ATTR=${FILESENDER_UID_ATTR:-EPPN}
      - CHOWN_WWW=${FILESENDER_CHOWN_WWW:-333:333}
      - DB_HOST=${FILESENDER_DB_HOST:-mysql}
      - DB_NAME=${FILESENDER_DB_NAME:-filesender}
      - DB_USER=${FILESENDER_DB_USER:-filesenderDBA}
      - DB_PASSWORD=${FILESENDER_DB_PASSWORD:-filesenderPSWD}
    volumes:
      - run.php:/run/php
      - ${FILESENDER_LOG_DIR:-./log/fpm}:/var/log/php-fpm
      - ${FILESENDER_DAT_DIR:-./persistant/filesender}:/data
      - filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp

  shib:
    build: ./shib
    restart: always
    volumes:
      - run.shibboleth:/run/shibboleth
      - ${SHIBBOLETH_ETC_DIR:-./shib/shibboleth}:/etc/shibboleth
      - ${SUPERVISOR_ETC_DIR:-./shib/supervisor/conf.d}:/etc/supervisor/conf.d
      - ${SUPERVISOR_DAT_DIR:-./shib/dip-display}:/opt/dip-display
      - ${SHIBBOLETH_LOG_DIR:-./log/shibboleth}:/var/log/shibboleth
      - ${SUPERVISOR_LOG_DIR:-./log/supervisor}:/var/log/supervisor
      - ${AMATICA_DAT_DIR:-am-pipeline-data}:/var/archivematica

  mysql:
    volumes:
      - "./mysql/create-filesender-db.sql:/docker-entrypoint-initdb.d/create-filesender-db.sql"
      
volumes:
  mysql_data:
    external:
      name: "am-mysql-data"
  elasticsearch_data:
    external:
      name: "am-elasticsearch-data"
  run.php:
  run.shibboleth:
  filesender:
  simplesaml:
