version: '2'
services:

  archivematica:
    image: 'uazlibraries/archivematica:1.6.1-beta4'
    restart: always
    links:
      - db-host
    ports:
      - "80:80"
      - "8000:8000"
    environment:
      - SMTP_DOMAIN=gmail.com
      - SMTP_SERVER=smtp.gmail.com:587
      - SMTP_FROM=dockertestfilesender@gmail.com
      - ADMIN_EMAIL=amatica_admin@gmail.com
      - AMATICA_NOSERVICE=mysql,logfile
      - DB_HOST=db-host
      - DB_USER=filesender
      - DB_PASSWORD=filesender
      - DB_DATABASE=MCP

  db-host:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=insecure
      - MYSQL_DATABASE=MCP
      - MYSQL_USER=filesender
      - MYSQL_PASSWORD=filesender
      - MYSQL_ALLOW_EMPTY_PASSWORD='false'
